# general settings
[flags]
show_table_scroll_position = true
enable_gpu_memory = true
left_legend = false

# custom btm layout
[[row]]
  ratio=30
  [[row.child]]
  type="cpu"
[[row]]
    ratio=30
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="temp"
      [[row.child.child]]
        type="disk"
    [[row.child]]
      ratio=4
      type="mem"
[[row]]
  ratio=30
  [[row.child]]
    type="net"
  [[row.child]]
    type="proc"
    default=true

# only show specified columns (too much info by default)
[processes]
columns = ["PID", "Name", "CPU%", "Mem%","User"]

# ignore some repeated temperature sensors
[temp_filter]
is_list_ignored = true
list = ["sensor", "Package"]
regex = false
case_sensitive = false
whole_word = false


